### ISSUE TITLE
Missing pretrained VGG16

### ISSUE THREAD

**Issue by vinits5** [zhaoyuzhi/deepfillv2#16]
Hey,

Great work and really appreciate for sharing the code.
I want to train deepfillv2 for RGB images. But, when I tried to train it on custom data it raises an error in line number 39 in utils.py file saying that NoFileFoundError for "./vgg16_pretrained.pth".
I looked for the file in your repository but was not able to find it. Can you please share the link for the file?
Thank you in advance.

**Comment by zhaoyuzhi** [comment]
Actually, it is the pre-trained model from torchvision. The link is https://portland-my.sharepoint.com/:u:/g/personal/yzzhao2-c_my_cityu_edu_hk/EQM9ue6KJJ5BnMhIGZPIXFEBoZNBgV8xA-_op7acm49usQ?e=SQb5nl

**Comment by vinits5** [comment]
Thank you @zhaoyuzhi.
It worked for me. I also figured out the way to use the pretrained VGG weights from torchvision.
