### ISSUE TITLE
what is the value of opt.lr?

### ISSUE THREAD

**Issue by erhuodaosi** [zhaoyuzhi/deepfillv2#2]
Wonderful work!
I am sorry to bother you,but I have a question about the value of opt.lr in train.py.

Traceback (most recent call last):
  File "train.py", line 62, in <module>
    trainer.WGAN_trainer(opt)
  File "/home/fl/deepfillv2/trainer.py", line 152, in WGAN_trainer
    adjust_learning_rate(optimizer_g, (epoch + 1), opt)
  File "/home/fl/deepfillv2/trainer.py", line 53, in adjust_learning_rate
    lr = opt.lr * (opt.lr_decrease_factor ** (epoch // opt.lr_decrease_epoch))
AttributeError: 'Namespace' object has no attribute 'lr'

I would very appreciate if you could help me,thank you!

**Comment by zhaoyuzhi** [comment]
Hi, I just updated trainer.py

Please check if it helps

**Comment by erhuodaosi** [comment]
For small image patches, make sure that all the dataset settings are the same as training part.

Why should we use the same dataset during the train and test stage rather than use train dataset  in train stage and use test dataset in test stage ?

**Comment by zhaoyuzhi** [comment]
I do not mean you need to use same dataset. I just recommend you use same mask settings on training set and validation set.

**Comment by erhuodaosi** [comment]
Thank you!I am so sorry to misunderstand your meaning.

**Comment by erhuodaosi** [comment]
1.
I have a request about ability to draw custom masks for single image evaluation. 
I wonder if it is possible to use custom masks rather than use free form mask for evaluation?
For example: Use a png or jpeg mask in the command line to remove a person or object from a nature photo.
2.
could we add some edge as input in this  implementation?
3.
What is the difference between your implementation and the author?
I am sorry to bother you,I would very appreciate if you could help me especially for the first question.
Thank you very much!

**Comment by zhaoyuzhi** [comment]
At least, the training set and testing set should be 'similar', or it is a domain adaption task.
You could refer to paper 'edge-connect'

**Comment by erhuodaosi** [comment]
Thank you for your information!
The generated masks are unpredictable,they are created by the way of "free-form mask" and they are different at different batches,even in the same batch,they are different.
But if given a real broken image,how could we inpaint it?

**Comment by zhaoyuzhi** [comment]
You should pre-define the mask. Or you may train a network automatically detect the broken parts.

By the way, if your real broken parts are different from free-form mask, I am not sure you can get a relatively good result.

**Comment by zhaoyuzhi** [comment]
I found a good demo based on NVIDIA's paper `partial conv`. Could you have a try for it? https://www.nvidia.com/research/inpainting/

**Comment by erhuodaosi** [comment]
Thank you for your suggestions!
I have tested on this website,it is really a good experience.Thank you for sharing it with me.I am so embarrassed and have no idea to pre-define the mask function.
I think the mask should be given by ourselves in the test stage,but it seems to use the generated mask  in replace.
Anyway,thank you very much!

**Comment by erhuodaosi** [comment]
Good news!
The official deepfillv2 have released!
We could remove a person or object by giving a mask picture.  
https://github.com/JiahuiYu/generative_inpainting
Good night!
Thank you very much!
