### ISSUE TITLE
Discriminator parameter not update?

### ISSUE THREAD

**Issue by usherbob** [zhaoyuzhi/deepfillv2#6]
Thanks for sharing your work. It seems like that you do not include optimizer.step in [trainer.py](https://github.com/zhaoyuzhi/deepfillv2/blob/master/deepfillv2/trainer.py#L112).

**Comment by zhaoyuzhi** [comment]
Thanks for point it out, you are right. I will add it.

**Comment by usherbob** [comment]
Huh, just feel amazing the model could be trained well without updating.
