### ISSUE TITLE
where is the Pre-trained model for RGB images?

### ISSUE THREAD

**Issue by GYTuuT** [zhaoyuzhi/deepfillv2#9]
hi, the 'deepfill2' folder on your Onedrive seems empty, only 'deepfill2_grayscale'  has some files

**Comment by zhaoyuzhi** [comment]
Thanks for your reply.
Yes, since I found that there are some problems of 'deepfillv2' models and codes, so I delete them.
I will re-train them as soon as possible.

**Comment by GYTuuT** [comment]
ok, thannks for your implementation
